### ISSUE TITLE
Error on line 1: Entity did not end with a semicolon

### ISSUE THREAD

**Issue by amirhusseinab** [bidsconvertr/bidsconvertr#1] opened 2023-09-11 10:54 UTC
R version: 4.3.1
Rstudio Version: 2023.06.2+561

Hi,

I get this error while creating the user_settings.R running convert_to_BIDS() command:
(zenity:55971): Gtk-WARNING **: 12:50:11.656: Failed to set text 'Please select your input folder now. It contains folders per session & subject or subject & session with the DICOM data. Your folder must be structured as follows: 

 'root/sessions/subjects/dicoms' 

 'root/subjects/sessions/dicoms'' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
Error in path.expand(path) : invalid 'path' argument

Looking forward to your comments.

Cheers,
Amir

**Comment by wulms** [comment] 2023-09-11 18:30
Dear Amir,

I am not able to reproduce the error. What is your OS?

I fixed today a bug - so please reinstall the package with:

`install_github("bidsconvertr/bidsconvertr")`

Could you try out the function below, select the relevant folder and send me the command line output of it?

`shinyDirectoryInput::choose.dir()`

Best, 
Niklas

**Comment by amirhusseinab** [comment] 2023-09-12 08:37
Hi Niklas,

I am using Ubuntu 22.04.3 LTS. The issue was still there using the updated "bidsconvertr" version. The problem is that after running convert_to_BIDS() and selecting "No, please create one for me", it does not open a window for me to select a location but an information box with "All updates are complete" is presented on the screen with the error message of the first comment on this issue in the console. No settings file is created then. That "invalid path argument" was shown because I canceled the input.

shinyDirectoryInput::choose.dir() works fine, it opens a window, and I can choose a folder. 

Amir

**Comment by wulms** [comment] 2023-09-12 19:14
Dear Amir,
I was finally able to reproduce the error on Ubuntu. The error lies in in the message box that was expected to print "&" but throws the mentioned error, if it is somewhere in the string.

Reproducible example:
`svDialogs::dlg_message("&")`

I fixed the error and replaced all '&' with 'and' in the message boxes and tested it locally.

Could you please reinstall the BIDSconvertR and keep me updated if the issue is fixed?

`remove.packages("bidsconvertr")`
`install_github("bidsconvertr/bidsconvertr")`

Best, 
Niklas

**Comment by amirhusseinab** [comment] 2023-09-12 19:41
Hey Niklas,

The issue is fixed. Thanks!

Cheers,
Amir

**Comment by wulms** [comment] 2023-09-12 19:44
You're welcome!
I am glad that it works now.

I close this issue. 

If you have any questions or feedback, just open a new one :)

**Closed as completed by wulms** 2023-09-12 19:44 UTC
